data_paths:
  events_folder: '../../data/bishkek_csr/03_train_ready/event_exports'
  respeck_folder: '../../data/bishkek_csr/03_train_ready/respeck'
  nasal_folder: '../../data/bishkek_csr/03_train_ready/nasal_files'
  features_folder: '../../data/bishkek_csr/03_train_ready/respeck_features'

apnea_event_labels:
  - 'Obstructive Apnea'

windowing:
  sampling_rate_hz: 12.5
  duration_sec: 30
  overlap_percentage: 0.80

feature_columns:
  - 'breathingSignal'
  - 'activityLevel'

# XGBoost Model Hyperparameters
xgboost_params:
  n_estimators: 200
  max_depth: 5
  learning_rate: 0.1
  objective: 'binary:logistic'
  subsample: 0.8
  colsample_bytree: 0.8
  eval_metric: 'logloss'
  use_label_encoder: False
  random_state: 42

windowing:
  feature_columns:
    - 'breathingSignal'
    - 'activityLevel'
    - 'RRV3MA'
  sampling_rate_hz: 12.5
  window_duration_sec: 30
  overlap_percentage: 0.80
  label_column: 'Label'
  session_id_column: 'SessionID'
  step_size:
# Training Parameters
training:
  random_state: 42

# W&B tracking
wandb:
  project_name: "dysfunctional-breathing-xgboost"
  run_name: "xgboost-cv-run-1"