name: breathing-characterisation
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  absl-py==2.3.0
  annotated-types==0.7.0
  astunparse==1.6.3
  attrs==25.3.0
  certifi==2025.4.26
  cffi==1.17.1
  charset-normalizer==3.4.2
  click==8.2.1
  contourpy==1.3.2
  cryptography==45.0.3
  cycler==0.12.1
  distro==1.9.0
  docker-pycreds==0.4.0
  fastjsonschema==2.21.1
  filelock==3.18.0
  flatbuffers==25.2.10
  fonttools==4.58.0
  fsspec==2025.5.1
  gast==0.6.0
  gitdb==4.0.12
  GitPython==3.1.44
  google-pasta==0.2.0
  grpcio==1.71.0
  h5py==3.13.0
  idna==3.10
  Jinja2==3.1.6
  joblib==1.5.1
  jsonschema==4.24.0
  jsonschema-specifications==2025.4.1
  keras==3.10.0
  kiwisolver==1.4.8
  lazy_loader==0.4
  libclang==18.1.1
  Markdown==3.8
  markdown-it-py==3.0.0
  MarkupSafe==3.0.2
  matplotlib==3.10.3
  mdurl==0.1.2
  ml_dtypes==0.5.1
  mne==1.9.0
  mpmath==1.3.0
  namex==0.1.0
  narwhals==1.41.1
  nbformat==5.10.4
  networkx==3.5
  numpy==2.1.3
  opt_einsum==3.4.0
  optree==0.15.0
  pandas==2.2.3
  pdfminer.six==20250327
  pdfplumber==0.11.6
  pillow==11.2.1
  plotly==6.1.2
  pooch==1.8.2
  protobuf==5.29.4
  pycparser==2.22
  pydantic==2.11.5
  pydantic_core==2.33.2
  pyparsing==3.2.3
  pypdfium2==4.30.1
  pytz==2025.2
  PyYAML==6.0.2
  referencing==0.36.2
  requests==2.32.3
  rich==14.0.0
  rpds-py==0.25.1
  scikit-learn==1.6.1
  scipy==1.15.3
  seaborn==0.13.2
  sentry-sdk==2.29.1
  setproctitle==1.3.6
  smmap==5.0.2
  sympy==1.14.0
  tabula-py==2.10.0
  tensorboard==2.19.0
  tensorboard-data-server==0.7.2
  tensorflow==2.19.0
  tensorflow-io-gcs-filesystem==0.37.1
  termcolor==3.1.0
  threadpoolctl==3.6.0
  torch==2.7.0
  torchaudio==2.7.0
  torchvision==0.22.0
  tqdm==4.67.1
  typing-inspection==0.4.1
  tzdata==2025.2
  urllib3==2.4.0
  wandb==0.19.11
  Werkzeug==3.1.3
  wrapt==1.17.2

